In [ ]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [7]:
from sklearn.model_selection import train_test_split
from sklearn import svm
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import accuracy_score

In [8]:
data =  pd.read_csv('/content/diabetes.csv')

In [9]:
data.head()

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
0,6,148,72,35,0,33.6,0.627,50,1
1,1,85,66,29,0,26.6,0.351,31,0
2,8,183,64,0,0,23.3,0.672,32,1
3,1,89,66,23,94,28.1,0.167,21,0
4,0,137,40,35,168,43.1,2.288,33,1

In [10]:
data.shape

(768, 9)

In [12]:
data['Outcome'].value_counts()

Outcome
0    500
1    268
Name: count, dtype: int64

In [13]:
Diabetes = data[data['Outcome']==0]
non_Diabetes =  data[data['Outcome']==1]

In [14]:
Diabetes.head()

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
1,1,85,66,29,0,26.6,0.351,31,0
3,1,89,66,23,94,28.1,0.167,21,0
5,5,116,74,0,0,25.6,0.201,30,0
7,10,115,0,0,0,35.3,0.134,29,0
10,4,110,92,0,0,37.6,0.191,30,0

In [15]:
non_Diabetes.head()

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
0,6,148,72,35,0,33.6,0.627,50,1
2,8,183,64,0,0,23.3,0.672,32,1
4,0,137,40,35,168,43.1,2.288,33,1
6,3,78,50,32,88,31.0,0.248,26,1
8,2,197,70,45,543,30.5,0.158,53,1

In [16]:
Diabetes.shape

(500, 9)

In [17]:
non_Diabetes.shape

(268, 9)

In [18]:
Diabetes_sample = Diabetes.sample(n=268)

In [22]:
new_data = pd.concat([Diabetes_sample,non_Diabetes],axis=0)

In [23]:
new_data.head()
new_data.shape

(536, 9)

In [24]:
new_data.head()

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
163,2,100,64,23,0,29.7,0.368,21,0
173,1,79,60,42,48,43.5,0.678,23,0
640,0,102,86,17,105,29.3,0.695,27,0
459,9,134,74,33,60,25.9,0.460,81,0
122,2,107,74,30,100,33.6,0.404,23,0

In [25]:
new_data['Outcome'].value_counts()

Outcome
0    268
1    268
Name: count, dtype: int64

In [26]:
new_data.describe()

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
count,536.000000,536.000000,536.000000,536.000000,536.000000,536.000000,536.000000,536.000000,536.000000
mean,4.029851,125.934701,70.164179,20.947761,84.402985,32.800560,0.499091,34.330224,0.500000
std,3.417799,31.866272,19.004945,16.468863,120.650069,7.932228,0.351497,11.752633,0.500467
min,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.078000,21.000000,0.000000
25%,1.000000,102.750000,64.000000,0.000000,0.000000,28.200000,0.254000,25.000000,0.000000
50%,3.000000,122.000000,72.000000,24.000000,36.500000,32.700000,0.396500,31.000000,0.500000
75%,6.000000,146.000000,80.000000,33.000000,132.750000,37.200000,0.673250,42.000000,1.000000
max,17.000000,199.000000,122.000000,99.000000,846.000000,67.100000,2.420000,81.000000,1.000000

In [27]:
new_data.groupby('Outcome').mean()

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age
Outcome,,,,,,,,
0,3.194030,110.611940,69.503731,19.731343,68.470149,30.458582,0.447683,31.593284
1,4.865672,141.257463,70.824627,22.164179,100.335821,35.142537,0.550500,37.067164

In [28]:
X= new_data.drop(columns='Outcome',axis=1)
Y= new_data['Outcome']

In [30]:
scaler = StandardScaler()

In [31]:
scaler.fit(X)

StandardScaler()

In [32]:
X = scaler.transform(X)

In [33]:
X_train,X_test,Y_train,Y_test = train_test_split(X,Y,test_size=0.2,stratify=Y,random_state=42)

In [34]:
classifier = svm.SVC(kernel='linear')

In [36]:
classifier.fit(X_train,Y_train)

SVC(kernel='linear')

In [37]:

X_train_pred =classifier.predict(X_train)
train_acc = accuracy_score(X_train_pred,Y_train)

In [38]:

X_test_pred =classifier.predict(X_test)
test_acc = accuracy_score(X_test_pred,Y_test)

In [39]:
train_acc

0.7827102803738317

In [41]:
test_acc

0.7407407407407407